#!/bin/bash

mkdir -p /problems/pdfcache
mkdir -p /problems/problems

if [ ! -d "/etc/letsencrypt/live/pcs.org.au/" ]; then
  certbot certonly --agree-tos -d pcs.org.au -m uwapcs@gmail.com --authenticator standalone
fi

certbot renew
/usr/bin/supervisord -n
