#!/bin/bash

mkdir -p /problems/pdfcache
mkdir -p /problems/problems

if [ ! -d "/etc/letsencrypt/live/pcs.ucc.asn.au/" ]; then
  certbot certonly --agree-tos -d pcs.ucc.asn.au -m uwapcs@gmail.com --authenticator standalone
fi

certbot renew
/usr/bin/supervisord -n
