apiVersion: v1
kind: Service
metadata:
  name: site
  labels:
    app: site
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
    - name: judge
      port: 9999
  selector:
    app: site
