apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: site
  labels:
    app: site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
        - image: uwapcs/dmoj-site
          name: site
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 9999
              name: judge
          volumeMounts:
            - name: problems-persistent-storage
              mountPath: /problems
            - name: site-ssl-persistent-storage
              mountPath: /etc/letsencrypt
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: site
                  key: django-secret
            - name: DMOJ_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: site
                  key: email-password
            - name: MYSQL_DMOJ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: dmoj-password
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "mkdir -p /problems/pdfcache;"
                  - "mkdir -p /problems/problems;"
      volumes:
        - name: problems-persistent-storage
          persistentVolumeClaim:
            claimName: problems
        - name: site-ssl-persistent-storage
          persistentVolumeClaim:
            claimName: site-ssl-volumeclaim
