apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  clusterIP: 10.245.255.50
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
