apiVersion: v1
kind: PersistentVolume
metadata:
  name: problems
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.245.255.50
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: problems
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
