apiVersion: v1
kind: Service
metadata:
  labels:
    app: site
  name: site-load-balancer
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30001
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: site
  sessionAffinity: None
  type: LoadBalancer
